version: "3.7"

# Compose for ur mongo instance
services:
  # Mongo instance directly
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      #- MONGO_INITDB_DATABASE=project

  # Mongo express, to view our database
  mongo-express:
    image: mongo-express
    restart: always
    environment:
      #- ME_CONFIG_MONGODB_SERVER=mongo
      #- ME_CONFIG_MONGODB_PORT=27017
      #- ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_OPTIONS_EDITORTHEME=material-darker
    depends_on:
      - mongo
    ports:
      - "8081:8081"
